"""
Django settings for MyProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

"""
Django settings for MyProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-)n)$k$&%*v$6!5ge4a+hsu01$k4473b99z7bik+2-131tj#p^8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*'] if DEBUG else os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')

# Gemini AI API Key
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'MyApp',
    'django_q',
]

SITE_ID = 1

# Triggering reload to pick up new templatetags

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'MyApp.middleware.AuditLogContextMiddleware',
]

ROOT_URLCONF = 'MyProject.urls'
TEMPLATES_dir = BASE_DIR / 'templates'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_dir],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MyApp.context_processors.categories',
                'MyApp.context_processors.support_context',
                'MyApp.context_processors.user_badges',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyProject.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
BANK_ACCOUNT = {
    'code': os.environ.get('BANK_CODE', '970418'),
    'account_number': os.environ.get('BANK_ACCOUNT_NUMBER', '5801569928'),
    'account_name': os.environ.get('BANK_ACCOUNT_NAME', 'PHAM QUOC HUY'),
}
VIETQR_CONFIG = {
    'use_dev': os.environ.get('VIETQR_USE_DEV', 'True').lower() == 'true',
    'client_id': os.environ.get('VIETQR_CLIENT_ID', 'af354177-fce4-4647-adb9-9a44e0518241'),
    'api_key': os.environ.get('VIETQR_API_KEY', '5b69bbe5-56a0-43a3-a63d-50f0b62d3616'),
}

# Casso webhook API key — get this from your Casso dashboard at casso.vn
# Leave empty during development (webhook won't require auth)
# In production, set this to match what Casso sends in the "Authorization: Apikey xxx" header
CASSO_APIKEY = os.environ.get('CASSO_APIKEY', '')  # Example: 'AK.xxxxxxxx.xxxxxxxxxx'

# ==================== ALLAUTH / GOOGLE LOGIN ====================
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    }
}

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# ==================== EMAIL (Gmail SMTP) ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@teazen.com')

# ==================== DJANGO Q2 & AUDIT LOG ====================
Q_CLUSTER = {
    'name': 'audit_cluster',
    'workers': 2,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'save_limit': 10000,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'sync': True,  # Execute tasks synchronously without needing a worker
    'orm': 'default'  # Using Django ORM as broker
}

# 32-byte URL-safe base64-encoded key for Fernet (cryptography)
AUDIT_LOG_ENCRYPTION_KEY = os.environ.get('AUDIT_LOG_ENCRYPTION_KEY', 'vOa3Q7yE-xL1o9D9uI6V-S8gE1W6eG5F-Y1E2nO9Z2c=')
