# Generated by Django 5.2.5 on 2026-01-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='storyboarditem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cabinetitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cabinet/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raw/'),
        ),
        migrations.AddField(
            model_name='storyboarditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storyboard/'),
        ),
    ]
