# Generated by Django 6.0.1 on 2026-02-02 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='MyApp.order')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('qr_bank', 'QR Code - Ngân hàng'), ('transfer', 'Chuyển khoản'), ('cash', 'Thanh toán tại chỗ'), ('wallet', 'Ví điện tử'), ('other', 'Khác')], default='qr_bank', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='MyApp.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_data', models.TextField()),
                ('payment_method', models.CharField(default='bank', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='MyApp.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
