# Generated by Django 6.0.1 on 2026-02-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_order_pdf_generated_invoice_payment_paymentqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
    ]
