# Generated by Django 6.0.1 on 2026-02-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Hóa đơn', 'verbose_name_plural': 'Danh sách hóa đơn'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên khách hàng'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_tax_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn thanh toán'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phát hành'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('issued', 'Đã phát hành'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế (VAT)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MyApp.invoice')),
            ],
        ),
    ]
