# Generated by Django 5.2.5 on 2026-03-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_comment_conversation_message_notification_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('discount_type', models.CharField(choices=[('percent', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định'), ('freeship', 'Miễn phí vận chuyển')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá trị giảm')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn hàng tối thiểu')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('valid_from', models.DateTimeField(verbose_name='Bắt đầu từ')),
                ('valid_to', models.DateTimeField(verbose_name='Kết thúc vào')),
                ('usage_limit', models.PositiveIntegerField(default=100, verbose_name='Số lượt sử dụng tối đa')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Số lượt đã sử dụng')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho biến thể')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='MyApp.product')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='MyApp.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công'), ('cancelled', 'Đã hủy')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='MyApp.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.productvariation'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.productvariation'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variation')},
        ),
    ]
