# Generated by Django 5.2.5 on 2026-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboarditem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung bài viết'),
        ),
    ]
