# Generated by Django 5.2.5 on 2026-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_storyboarditem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Đường link khi click vào item này (VD: /product/slug/)', max_length=500, null=True),
        ),
    ]
