# Generated by Django 5.2.5 on 2026-03-11 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công'), ('return_requested', 'Yêu cầu trả hàng'), ('return_approved', 'Đã duyệt trả hàng'), ('returned', 'Đã nhận hàng trả'), ('refunded', 'Đã hoàn tiền'), ('exchanged', 'Đã đổi hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='MyApp.product'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công'), ('return_requested', 'Yêu cầu trả hàng'), ('return_approved', 'Đã duyệt trả hàng'), ('returned', 'Đã nhận hàng trả'), ('refunded', 'Đã hoàn tiền'), ('exchanged', 'Đã đổi hàng'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('refund', 'Hoàn tiền'), ('exchange', 'Đổi hàng'), ('cancel', 'Hủy đơn (Sau khi thanh toán)')], default='refund', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã chấp nhận'), ('rejected', 'Từ chối'), ('completed', 'Hoàn tất')], default='pending', max_length=20)),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú của Admin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='returns/', verbose_name='Ảnh minh chứng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='MyApp.order')),
            ],
            options={
                'verbose_name': 'Yêu cầu đổi trả',
                'verbose_name_plural': 'Yêu cầu đổi trả',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason_detail', models.CharField(blank=True, max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='MyApp.returnrequest')),
            ],
        ),
    ]
