# Generated by Django 5.2.5 on 2026-03-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_alter_order_status_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Lượt hữu ích'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Ảnh đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MyApp.review')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
