# Generated by Django 6.0.1 on 2026-03-11 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_product_images_and_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review', 'Đánh giá mới'), ('comment', 'Bình luận mới'), ('reply', 'Phản hồi bình luận'), ('message', 'Tin nhắn mới'), ('order', 'Cập nhật đơn hàng'), ('system', 'Hệ thống'), ('promotion', 'Khuyến mãi'), ('wishlist', 'Sản phẩm yêu thích'), ('stock', 'Cập nhật tồn kho')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='MyApp_notif_user_id_aad60f_idx'),
        ),
    ]
