# Generated by Django 5.2.5 on 2026-03-11 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_notification_overhaul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], unique=True)),
                ('open_time', models.TimeField(default='08:00')),
                ('close_time', models.TimeField(default='22:00')),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Giờ hỗ trợ',
                'verbose_name_plural': 'Giờ hỗ trợ theo ngày',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='SupportQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Nhãn nút')),
                ('content', models.TextField(verbose_name='Nội dung template')),
                ('category', models.CharField(choices=[('greeting', 'Chào hỏi'), ('inquiry', 'Hỏi thông tin'), ('resolution', 'Giải quyết vấn đề'), ('closing', 'Kết thúc'), ('other', 'Khác')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Reply',
                'verbose_name_plural': 'Quick Replies',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Khách hàng'), ('agent', 'Nhân viên'), ('bot', 'Bot tự động'), ('system', 'Hệ thống')], max_length=10)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False)),
                ('is_internal', models.BooleanField(default=False, verbose_name='Ghi chú nội bộ (agent only)')),
                ('client_msg_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn hỗ trợ',
                'verbose_name_plural': 'Tin nhắn hỗ trợ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_attachments/%Y/%m/', verbose_name='File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('file_type', models.CharField(choices=[('image', 'Hình ảnh'), ('document', 'Tài liệu')], default='image', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='MyApp.supportmessage')),
            ],
            options={
                'verbose_name': 'File đính kèm',
                'verbose_name_plural': 'File đính kèm',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session key (khách vãng lai)')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Tên khách vãng lai')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email khách vãng lai')),
                ('subject', models.CharField(default='Hỗ trợ chung', max_length=200, verbose_name='Tiêu đề')),
                ('category', models.CharField(choices=[('order', 'Đơn hàng'), ('payment', 'Thanh toán'), ('return', 'Đổi trả / Hoàn hàng'), ('product', 'Thông tin sản phẩm'), ('shipping', 'Vận chuyển'), ('account', 'Tài khoản'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Chủ đề')),
                ('status', models.CharField(choices=[('open', 'Khởi tạo'), ('waiting', 'Đang chờ nhân viên'), ('assigned', 'Đang hỗ trợ'), ('resolved', 'Đã giải quyết'), ('closed', 'Đã đóng')], default='open', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', max_length=20, verbose_name='Ưu tiên')),
                ('source', models.CharField(default='widget', max_length=20, verbose_name='Kênh liên hệ')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm phản hồi đầu tiên')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm giải quyết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng (đã login)')),
            ],
            options={
                'verbose_name': 'Ticket hỗ trợ',
                'verbose_name_plural': 'Ticket hỗ trợ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét (tùy chọn)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='MyApp.supportticket')),
            ],
            options={
                'verbose_name': 'Đánh giá hỗ trợ',
                'verbose_name_plural': 'Đánh giá hỗ trợ',
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='MyApp.supportticket'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-updated_at'], name='support_ticket_status_updated'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_ticket_user_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['session_key', 'status'], name='support_ticket_session_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_ticket_agent_status'),
        ),
    ]
