# Generated by Django 5.2.5 on 2026-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_userprofile_district_userprofile_district_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('admin', 'Administrator'), ('accountant', 'Kế toán'), ('warehouse', 'Nhân viên kho')], default='customer', max_length=20, verbose_name='Vai trò'),
        ),
    ]
