# Generated by Django 5.2.5 on 2026-03-20 15:23

import MyApp.audit_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_orderstatushistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Log ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Loại sự kiện')),
                ('severity_level', models.CharField(choices=[('INFO', 'Thông tin'), ('WARNING', 'Cảnh báo'), ('ERROR', 'Lỗi'), ('CRITICAL', 'Nghiêm trọng')], default='INFO', max_length=20, verbose_name='Mức độ')),
                ('actor_id', models.IntegerField(blank=True, null=True, verbose_name='User/Account ID')),
                ('actor_role', models.CharField(blank=True, max_length=50, verbose_name='Vai trò')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='Loại tài nguyên')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID Tài nguyên')),
                ('before_state', MyApp.audit_models.EncryptedTextField(blank=True, verbose_name='Dữ liệu Cũ')),
                ('after_state', MyApp.audit_models.EncryptedTextField(blank=True, verbose_name='Dữ liệu Mới')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do chi tiết')),
                ('previous_hash', models.CharField(blank=True, max_length=64, verbose_name='Mã băm liền trước')),
                ('current_hash', models.CharField(blank=True, max_length=64, verbose_name='Mã băm hiện tại')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận (Đã giữ hàng)'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công (Đã trừ kho)'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy'), ('return_requested', 'Yêu cầu trả hàng'), ('return_approved', 'Đã duyệt trả hàng'), ('returned', 'Đã nhận hàng trả'), ('refunded', 'Đã hoàn tiền'), ('exchanged', 'Đã đổi hàng')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận (Đã giữ hàng)'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao'), ('delivered', 'Thành công (Đã trừ kho)'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy'), ('return_requested', 'Yêu cầu trả hàng'), ('return_approved', 'Đã duyệt trả hàng'), ('returned', 'Đã nhận hàng trả'), ('refunded', 'Đã hoàn tiền'), ('exchanged', 'Đã đổi hàng')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('qr_bank', 'QR Code - Ngân hàng'), ('transfer', 'Chuyển khoản'), ('cash', 'Thanh toán tại chỗ'), ('cod', 'Thanh toán khi nhận hàng (COD)'), ('wallet', 'Ví điện tử'), ('other', 'Khác')], default='qr_bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('cod_pending', 'Thu tiền khi giao hàng'), ('pending_verification', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='physical_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn vật lý'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='physical_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn vật lý biến thể'),
        ),
    ]
